package com.rest.api.enums

enum class ErrorCodes {
    CONTACT_ALREADY_EXIST,
    FIRST_NAME_CANNOT_BE_NULL,
    LAST_NAME_CANNOT_BE_NULL,
    BIRTH_DATE_CANNOT_BE_NULL,
    BIRTH_DATE_INVALID_FORMAT
}
